<div>
<img src="https://www.ul.ie/themes/custom/ul/logo.jpg" />
</div>

#**MSc in Artificial Intelligence and Machine Learning**
##CS6271 - Evolutionary Algorithms and Humanoid Robotics 2023
### Kaggle Competition


Module Leader: Conor Ryan

Developer: Allan De Lima

Link to access the competition: https://www.kaggle.com/competitions/cs6271-20234-final-project

Link to join the competition: https://www.kaggle.com/t/2b316ba38c144f23ac780c8fc898b4d7



## Introduction

Predict whether income exceeds $50K/yr based on census data. This is a shorter version of the also known as "Census Income" dataset (donated on 4/30/1996).

In [ ]:
# Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

Class:

income: >50K, <=50K.


Listing of features:

age: continuous.

workclass: categorical (Private, Self-emp-not-inc, Local-gov, State-gov).

education: categorical (Bachelors, Some-college, HS-grad, Masters, Doctorate).

marital-status: categorical (Married-civ-spouse, Divorced, Never-married).

relationship: categorical (Wife, Husband, Not-in-family, Other-relative).

race: categorical (White, Asian-Pac-Islander, Black).

sex: categorical (Female, Male).

capital-gain: continuous.

capital-loss: continuous.

hours-per-week: continuous.

native-country: categorical (United-States, Others).


### Load the dataset

In [ ]:
# Suppressing Warnings:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
## mount your Google drive
# 1) run this cell
# 2) sign in
# 3) verify your drive is mounted

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [ ]:
%ls /content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/

 Activity/
'Conor Ryan, Michael O'\''Neill, JJ Collins - Handbook of Grammatical Evolution-Springer International Publishing (2018).pdf'
 grape/
 IntroductionToEvolutionaryComp_2015.pdf
 Notes/
 Project/
 StudyNotes/


Clone the GRAPE repository at first because the dataset to be used is already there.

In [ ]:

import os
# Get the library from our BDS research Group
# copy the path from your drive
PATH = '/content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/'

# check if 'grape' already exists
if os.path.exists(PATH + 'grape'):
    print('grape directory already exists')
else:
    %cd /content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/
    !git clone https://github.com/bdsul/grape.git
    print('Cloning grape in your Drive')

# change directory to 'grape'
%cd /content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/

grape directory already exists
/content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC


Now you have a grape folder in your Drive account.

Upload the files adult_training.csv and adult_test.csv to the folder grape/datasets in your Drive before running the next cells.

### Train set

In [ ]:
train_file = 'Project/adult_training.csv'

In [ ]:
# load train set
df_train = pd.read_csv(PATH+train_file)
df_train.head()

age         workclass  education      marital-status   relationship   race  \
0   28           Private  Bachelors       Never-married  Not-in-family  White   
1   34  Self-emp-not-inc  Bachelors  Married-civ-spouse        Husband  Black   
2   32           Private  Bachelors       Never-married  Not-in-family  Black   
3   46           Private  Bachelors            Divorced  Not-in-family  White   
4   44           Private  Bachelors  Married-civ-spouse        Husband  White   

      sex  capital-gain  capital-loss  hours-per-week native-country income  
0    Male             0             0              40  United-States  <=50K  
1    Male             0          1887              48  United-States   >50K  
2  Female             0             0              40  United-States  <=50K  
3    Male             0             0              40         Others  <=50K  
4    Male             0             0              50  United-States   >50K

In [65]:
df_train['native-country'].value_counts()

United-States    4765
Others            435
Name: native-country, dtype: int64

In [ ]:
df_train.describe()

age  capital-gain  capital-loss  hours-per-week
count  5200.000000    5200.00000   5200.000000     5200.000000
mean     39.688077    1059.89500    109.486346       42.786538
std      11.973363    6687.36408    442.694051       10.937644
min      17.000000       0.00000      0.000000        1.000000
25%      30.000000       0.00000      0.000000       40.000000
50%      38.000000       0.00000      0.000000       40.000000
75%      48.000000       0.00000      0.000000       48.000000
max      90.000000   99999.00000   2559.000000       99.000000

In [ ]:
X_train = df_train.copy()
# warning: cannot drop it more than once
X_train.drop(['income'], axis=1, inplace=True)

You should represent the outputs with 0 where the income is smaller or equal to 50K and with 1 if it is greater than 50K.

Follow exactly this approach, because the test targets are represented like this in the competition.

In [ ]:
# class labels
l, _ = X_train.shape

y_train = np.zeros([l,], dtype=int)

for i in range(l):
  if df_train['income'].iloc[i] == '>50K':
    y_train[i] = 1
  elif df_train['income'].iloc[i] == '<=50K':
    y_train[i] = 0

In [ ]:
print(y_train[0:5]) #print head

[0 1 0 0 1]


### Test set

In [ ]:
test_file = 'Project/adult_test.csv'

In [ ]:
# load test set
df_test = pd.read_csv(PATH+test_file)
df_test.head(50)

age         workclass     education      marital-status    relationship  \
0    33           Private       HS-grad       Never-married   Not-in-family   
1    58           Private       HS-grad  Married-civ-spouse         Husband   
2    30  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
3    26           Private  Some-college       Never-married   Not-in-family   
4    43         State-gov       HS-grad       Never-married   Not-in-family   
5    36           Private  Some-college            Divorced   Not-in-family   
6    52  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
7    37           Private       HS-grad  Married-civ-spouse         Husband   
8    36           Private  Some-college  Married-civ-spouse         Husband   
9    40           Private     Doctorate  Married-civ-spouse         Husband   
10   27           Private       HS-grad       Never-married   Not-in-family   
11   50           Private       HS-grad  Married-civ-spouse         Husband   
12   24           Private       HS-grad  Married-civ-spouse         Husband   
13   33           Private       HS-grad       Never-married   Not-in-family   
14   55           Private  Some-college  Married-civ-spouse            Wife   
15   38           Private       HS-grad  Married-civ-spouse         Husband   
16   31           Private  Some-college       Never-married   Not-in-family   
17   50         Local-gov  Some-college  Married-civ-spouse         Husband   
18   48         State-gov       Masters  Married-civ-spouse         Husband   
19   45           Private  Some-college  Married-civ-spouse         Husband   
20   39  Self-emp-not-inc       HS-grad  Married-civ-spouse            Wife   
21   23         Local-gov     Bachelors       Never-married  Other-relative   
22   31           Private  Some-college       Never-married   Not-in-family   
23   33           Private       HS-grad  Married-civ-spouse         Husband   
24   25           Private     Bachelors       Never-married   Not-in-family   
25   55         Local-gov       Masters  Married-civ-spouse         Husband   
26   48           Private     Bachelors  Married-civ-spouse         Husband   
27   35           Private       Masters       Never-married   Not-in-family   
28   34           Private       HS-grad  Married-civ-spouse         Husband   
29   36           Private       HS-grad  Married-civ-spouse         Husband   
30   75  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
31   46         Local-gov       HS-grad  Married-civ-spouse         Husband   
32   29           Private       HS-grad       Never-married   Not-in-family   
33   50  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
34   33           Private       Masters       Never-married   Not-in-family   
35   58           Private     Bachelors  Married-civ-spouse         Husband   
36   30           Private     Bachelors       Never-married   Not-in-family   
37   50           Private     Bachelors  Married-civ-spouse         Husband   
38   21           Private  Some-college  Married-civ-spouse         Husband   
39   46         Local-gov  Some-college  Married-civ-spouse         Husband   
40   32           Private     Bachelors  Married-civ-spouse         Husband   
41   40  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
42   45           Private     Bachelors  Married-civ-spouse            Wife   
43   42           Private  Some-college  Married-civ-spouse         Husband   
44   68           Private     Doctorate  Married-civ-spouse         Husband   
45   37           Private       HS-grad  Married-civ-spouse            Wife   
46   36  Self-emp-not-inc       HS-grad  Married-civ-spouse         Husband   
47   59           Private       HS-grad  Married-civ-spouse         Husband   
48   22           Private  Some-college       Never-married   Not-in-family   
49   50         Local-gov  Some-college  Married-civ-s

In [ ]:
df_test.describe()

age  capital-gain  capital-loss  hours-per-week
count  10402.000000  10402.000000  10402.000000    10402.000000
mean      39.811575   1280.969237    106.101038       42.749567
std       12.063746   7826.438595    438.826968       11.200949
min       18.000000      0.000000      0.000000        1.000000
25%       30.000000      0.000000      0.000000       40.000000
50%       38.000000      0.000000      0.000000       40.000000
75%       48.000000      0.000000      0.000000       48.000000
max       90.000000  99999.000000   3683.000000       99.000000

In [ ]:
X_test = df_test.copy()

You will need to prepare both training and test datasets before working with a Machine Learning method.

Consider you need to use some encoding method with categorical data.

You are free to use any other pre-processing ideas.

In [ ]:
X_train.columns

Index(['age', 'workclass', 'education', 'marital-status', 'relationship',
       'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',
       'native-country'],
      dtype='object')

In [ ]:
X_test.columns

Index(['age', 'workclass', 'education', 'marital-status', 'relationship',
       'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',
       'native-country'],
      dtype='object')

In [ ]:
# Encode the training data
X_train_encoded = pd.get_dummies(X_train, columns=['workclass', 'education', 'marital-status', 'relationship', 'race', 'sex', 'native-country'], drop_first=True)

# Encode the test data
X_test_encoded = pd.get_dummies(X_test, columns=['workclass', 'education', 'marital-status', 'relationship', 'race', 'sex', 'native-country'], drop_first=True)

# Align the columns in the test set to match the train set
# This adds missing dummy columns to the test set with default value of 0
# and ensures the order of columns matches the training set
X_test_encoded = X_test_encoded.reindex(columns=X_train_encoded.columns, fill_value=0)


In [ ]:
X_train_encoded['workclass'].value

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'workclass'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-66-c3ad2d73b9f8>", line 1, in <cell line: 1>
    X_train_encoded['workclass'].value_counts()
  File "/usr/local/

In [ ]:
X_train_encoded.head(5)

age  capital-gain  capital-loss  hours-per-week  workclass_Private  \
0   28             0             0              40                  1   
1   34             0          1887              48                  0   
2   32             0             0              40                  1   
3   46             0             0              40                  1   
4   44             0             0              50                  1   

   workclass_Self-emp-not-inc  workclass_State-gov  education_Doctorate  \
0                           0                    0                    0   
1                           1                    0                    0   
2                           0                    0                    0   
3                           0                    0                    0   
4                           0                    0                    0   

   education_HS-grad  education_Masters  education_Some-college  \
0                  0                  0                       0   
1                  0                  0                       0   
2                  0                  0                       0   
3                  0                  0                       0   
4                  0                  0                       0   

   marital-status_Married-civ-spouse  marital-status_Never-married  \
0                                  0                             1   
1                                  1                             0   
2                                  0                             1   
3                                  0                             0   
4                                  1                             0   

   relationship_Not-in-family  relationship_Other-relative  relationship_Wife  \
0                           1                            0                  0   
1                           0                            0                  0   
2                           1                            0                  0   
3                           1                            0                  0   
4                           0                            0                  0   

   race_Black  race_White  sex_Male  native-country_United-States  
0           0           1         1                             1  
1           1           0         1                             1  
2           1           0         0                             1  
3           0           1         1                             0  
4           0           1         1                             1

In [ ]:
X_test_encoded.head(5)

age  capital-gain  capital-loss  hours-per-week  workclass_Private  \
0   33          3325             0              50                  1   
1   58             0             0              40                  1   
2   30             0             0              60                  0   
3   26             0             0              20                  1   
4   43             0             0              60                  0   

   workclass_Self-emp-not-inc  workclass_State-gov  education_Doctorate  \
0                           0                    0                    0   
1                           0                    0                    0   
2                           1                    0                    0   
3                           0                    0                    0   
4                           0                    1                    0   

   education_HS-grad  education_Masters  education_Some-college  \
0                  1                  0                       0   
1                  1                  0                       0   
2                  1                  0                       0   
3                  0                  0                       1   
4                  1                  0                       0   

   marital-status_Married-civ-spouse  marital-status_Never-married  \
0                                  0                             1   
1                                  1                             0   
2                                  1                             0   
3                                  0                             1   
4                                  0                             1   

   relationship_Not-in-family  relationship_Other-relative  relationship_Wife  \
0                           1                            0                  0   
1                           0                            0                  0   
2                           0                            0                  0   
3                           1                            0                  0   
4                           1                            0                  0   

   race_Black  race_White  sex_Male  native-country_United-States  
0           0           1         1                             1  
1           0           1         1                             1  
2           0           1         1                             1  
3           0           1         0                             1  
4           0           1         1                             1

Convert the datasets to NumPy to easily use them.

In [ ]:
# data features
X_train_encoded_new = X_train_encoded.to_numpy()
X_test_encoded_new = X_test_encoded.to_numpy()


In [ ]:
X_train_encoded_new.shape

(5200, 20)

In [ ]:
len(X_train_encoded.columns.tolist())

20

In [ ]:
X_test_encoded_new.shape

(10402, 20)

In [ ]:
len(X_test_encoded.columns.tolist())

20

## GRAPE


GRammatical Algorithms in Python for Evolution (GRAPE)


In [ ]:
!pip install deap

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 3.4 MB/s eta 0:00:00


In [ ]:
%cd /content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/grape

/content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/grape


In [ ]:
import grape
import algorithms

from os import path
from deap import creator, base, tools
import random
import csv

You can import functions to be used with your grammar from [functions.py](https://github.com/UL-BDS/grape/blob/main/functions.py) on GRAPE repository and / or you can define your own functions.

In [ ]:
# from functions import add, sub, mul, pdiv#, psqrt, plog, neg, and_, or_, not_, less_than_or_equal, greater_than_or_equal
from functions import add, sub, mul, pdiv, psin, pcos, plog, psqrt, minimum, maximum, sigmoid, not_, and_, or_, nand_, nor_, greater_than_or_equal, less_than_or_equal, if_



'heartDisease.bnf' is a grammar used for another problem just to check if everything is working well.

Write your own grammar in a text file and save it in your Drive account.

Put the whole address on GRAMMAR_FILE and print to check it.

In [ ]:
# Define the grammar as a multi-line string
grammar = """
<log_op> ::= <conditional_branches> | and_(<log_op>,<log_op>) | or_(<log_op>,<log_op>) | not_(<log_op>) | <boolean_feature>
<conditional_branches> ::= less_than_or_equal(<num_op>,<num_op>) | greater_than_or_equal(<num_op>, <num_op>)
<num_op>   ::= add(<num_op>,<num_op>) | sub(<num_op>,<num_op>) | mul(<num_op>,<num_op>) | pdiv(<num_op>,<num_op>) | <nonboolean_feature>
<boolean_feature> ::= x[4] | x[5] | x[6] | x[7] | x[8] | x[9] | x[10] | x[11] | x[12] | x[13] | x[14] | x[15] | x[16] | x[17] | x[18] | x[19]
<nonboolean_feature> ::= x[0] | x[1] | x[2] | x[3] |<c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9

"""

# Write the grammar to a file
grammar_file_path = PATH + 'grape/grammars/adult_grammar.bnf'  # A path in the writable directory
with open(grammar_file_path, 'w') as file:
    file.write(grammar)

# # Inform the user
print(f"Grammar has been written to {grammar_file_path}")

Grammar has been written to /content/drive/MyDrive/CourseNotebooks/CS6271_EC_HR/EC/grape/grammars/adult_grammar.bnf


In [ ]:
GRAMMAR_FILE = PATH + 'grape/grammars/adult_grammar.bnf' #put the whole address of your own grammar and remove the # in the beginning of this line
# GRAMMAR_FILE = 'custom_grammar.bnf' #remove this line when you are using your own grammar

f = open(GRAMMAR_FILE, "r") #remove the # in the beginning of this line when you are using your own grammar
# f = open("grammars/" + GRAMMAR_FILE, "r") #remove this line when you are using your own grammar
print(f.read())
f.close()


<log_op> ::= <conditional_branches> | and_(<log_op>,<log_op>) | or_(<log_op>,<log_op>) | not_(<log_op>) | <boolean_feature>
<conditional_branches> ::= less_than_or_equal(<num_op>,<num_op>) | greater_than_or_equal(<num_op>, <num_op>)
<num_op>   ::= add(<num_op>,<num_op>) | sub(<num_op>,<num_op>) | mul(<num_op>,<num_op>) | pdiv(<num_op>,<num_op>) | <nonboolean_feature>
<boolean_feature> ::= x[4] | x[5] | x[6] | x[7] | x[8] | x[9] | x[10] | x[11] | x[12] | x[13] | x[14] | x[15] | x[16] | x[17] | x[18] | x[19]
<nonboolean_feature> ::= x[0] | x[1] | x[2] | x[3] |<c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9




Run the following cell to put your grammar on the class Grammar.

In [ ]:
BNF_GRAMMAR = grape.Grammar(GRAMMAR_FILE) #remove the # in the beginning of this line when you are using your own grammar
# BNF_GRAMMAR = grape.Grammar(path.join("grammars", GRAMMAR_FILE)) #remove this line when you are using your own grammar

The fitness function here is the percentage of outputs wrongly predicted.

You can write your own fitness function if you prefer.

In [ ]:
def fitness_eval(individual, points):
    """
    Fitness Function
    """

    x = points[0]
    Y = points[1]

    if individual.invalid == True:
        return np.NaN,

    # print("AAAA")
    print("Evaluating phenotype:", individual.phenotype)

    # Evaluate the expression
    try:


        pred = eval(individual.phenotype)
    except (FloatingPointError, ZeroDivisionError, OverflowError,
            MemoryError):
        return np.NaN,
    assert np.isrealobj(pred)

    compare = np.equal(Y,pred)
    fitness = 1 - np.mean(compare)

    return fitness,

To use properly the fitness function above with GRAPE, the features must be in the lines, and the samples must be in the columns, so if your data is not like that, you need to transpose the matrix.

Take a look at the print. If you run this cell two times, the matrix will be transposed again and will not work properly.

In [ ]:
X_train_encoded_new = np.transpose(X_train_encoded_new)
X_test_encoded_new = np.transpose(X_test_encoded_new)



print('Training (X,Y):\t', X_train_encoded_new.shape, y_train.shape)
print('Test (X):\t', X_test_encoded_new.shape)

Training (X,Y):	 (20, 5200) (5200,)
Test (X):	 (20, 10402)


Set the Grammatical Evolution parameters.

Make sure you set a random seed just in case we need to re-run your experiments.

In [ ]:
# Hyperparameters
POPULATION_SIZE = 1000
MAX_GENERATIONS = 100
P_CROSSOVER = 0.6
P_MUTATION = 0.04
ELITE_SIZE = 1
HALL_OF_FAME_SIZE = 1

TOURNAMENT_SIZE = 3
RANDOM_SEED = 42



MAX_GENOME_LENGTH = None  # Adjust this if necessary

# Other parameters may remain as defined in your code


# Other necessary imports and setup code here...

# Continue setting the hyperparameters
# MAX_INIT_TREE_DEPTH = 6
# MIN_INIT_TREE_DEPTH = 2
# MAX_TREE_DEPTH = 10
MAX_GENOME_LENGTH = 100  # Adjust this if necessary
MAX_WRAPS = 0
CODON_SIZE = 255

REPORT_ITEMS = ['gen', 'invalid', 'avg', 'std', 'min', 'max',
                'best_ind_length', 'avg_length',
                'best_ind_nodes', 'avg_nodes',
                'best_ind_depth', 'avg_depth',
                'avg_used_codons', 'best_ind_used_codons',
                'structural_diversity', 'fitness_diversity',
                'selection_time', 'generation_time']

Create a toolbox.

In [ ]:
toolbox = base.Toolbox()

# define a single objective, minimising fitness strategy:
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))

creator.create('Individual', grape.Individual, fitness=creator.FitnessMin)

toolbox.register("populationCreator", grape.sensible_initialisation, creator.Individual)

toolbox.register("evaluate", fitness_eval)

# Tournament selection:
toolbox.register("select", tools.selTournament, tournsize=TOURNAMENT_SIZE)

# Single-point crossover:
toolbox.register("mate", grape.crossover_onepoint)

# Flip-int mutation:
toolbox.register("mutate", grape.mutation_int_flip_per_codon)

In [ ]:
# create initial population (generation 0):

MAX_INIT_TREE_DEPTH = 14
MIN_INIT_TREE_DEPTH = 5
MAX_TREE_DEPTH = 20



CODON_CONSUMPTION = 'lazy'  # Lazy consumption of codons
GENOME_REPRESENTATION = 'list'  # Linear genome representation


population = toolbox.populationCreator(pop_size=POPULATION_SIZE,
                                           bnf_grammar=BNF_GRAMMAR,
                                           min_init_depth=MIN_INIT_TREE_DEPTH,
                                           max_init_depth=MAX_INIT_TREE_DEPTH,
                                           codon_size=CODON_SIZE,
                                           codon_consumption=CODON_CONSUMPTION,
                                           genome_representation=GENOME_REPRESENTATION
                                            )


# define the hall-of-fame object:
hof = tools.HallOfFame(HALL_OF_FAME_SIZE)

# prepare the statistics object:
stats = tools.Statistics(key=lambda ind: ind.fitness.values)
stats.register("avg", np.nanmean)
stats.register("std", np.nanstd)
stats.register("min", np.nanmin)
stats.register("max", np.nanmax)

Run Grammatical Evolution.

In [ ]:
population, logbook = algorithms.ge_eaSimpleWithElitism(population, toolbox, cxpb=P_CROSSOVER, mutpb=P_MUTATION,
                                              ngen=MAX_GENERATIONS, elite_size=ELITE_SIZE,
                                              bnf_grammar=BNF_GRAMMAR,
                                              codon_size=CODON_SIZE,
                                              max_tree_depth=MAX_TREE_DEPTH,
                                              max_genome_length=MAX_GENOME_LENGTH,
                                              points_train=[X_train_encoded_new, y_train],
                                              codon_consumption=CODON_CONSUMPTION,
                                              report_items=REPORT_ITEMS,
                                              genome_representation=GENOME_REPRESENTATION,
                                              stats=stats, halloffame=hof, verbose=False)

Streaming output truncated to the last 5000 lines.
Evaluating phenotype: not_(or_(or_(or_(x[8],x[13]),x[15]),or_(x[16],x[10])))
Evaluating phenotype: not_(or_(and_(or_(x[17],greater_than_or_equal(mul(75.04,x[1]), x[2])),x[13]),or_(x[8],not_(not_(x[10])))))
Evaluating phenotype: not_(or_(x[15],x[7]))
Evaluating phenotype: x[15]
Evaluating phenotype: greater_than_or_equal(mul(mul(x[1],add(mul(x[3],94.08),x[0])),x[3]), x[1])
Evaluating phenotype: not_(or_(x[13],greater_than_or_equal(x[0], x[2])))
Evaluating phenotype: not_(or_(or_(x[13],or_(x[8],x[10])),x[13]))
Evaluating phenotype: not_(or_(or_(not_(x[14]),x[8]),x[13]))
Evaluating phenotype: not_(or_(or_(x[8],x[10]),not_(x[12])))
Evaluating phenotype: or_(or_(x[13],and_(x[15],x[13])),or_(x[18],x[10]))
Evaluating phenotype: not_(or_(or_(x[13],or_(x[10],x[13])),x[8]))
Evaluating phenotype: not_(greater_than_or_equal(add(x[2],40.79), mul(x[3],24.28)))
Evaluating phenotype: not_(or_(or_(x[10],or_(x[13],or_(x[5],or_(x[8],x[10])))),x[15]))
Eva

Show the best individual as an expression.

In [ ]:
# Best individual
import textwrap
best = hof.items[0].phenotype
print("Best individual: \n","\n".join(textwrap.wrap(best,80)))
print("\nTraining Fitness: ", hof.items[0].fitness.values[0])
print("Depth: ", hof.items[0].depth)
print("Length of the genome: ", len(hof.items[0].genome))
print(f'Used portion of the genome: {hof.items[0].used_codons/len(hof.items[0].genome):.2f}')

Best individual: 
 and_(or_(x[7],x[11]),not_(or_(or_(x[10],x[8]),not_(not_(x[14])))))

Training Fitness:  0.23769230769230765
Depth:  8
Length of the genome:  77
Used portion of the genome: 0.22


Define a function to predict values, without comparing to expected outputs.

In [ ]:
def predict(individual, X):
    x = X
    print(x)

    if individual.invalid == True:
        return np.NaN,

    # Evaluate the expression
    try:
        pred = eval(individual.phenotype)
    except (FloatingPointError, ZeroDivisionError, OverflowError,
            MemoryError):
        return np.NaN,
    assert np.isrealobj(pred)

    return pred

Predict the classes of the test set.

Make sure you print here in the notebook you will submit to Brightspace the same predictions you used in your best submission to the Kaggle competition.

In [ ]:
y_pred = predict(hof.items[0], X_test_encoded_new)
print("Predicted classes of the test set: ", y_pred)

[[  33   58   30 ...   40   40   53]
 [3325    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   1    1    1 ...    1    1    1]
 [   1    1    1 ...    1    1    0]
 [   1    1    1 ...    1    1    1]]
Predicted classes of the test set:  [False False False ... False False False]


In [ ]:
y_pred.tolist()

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 

Write a code to create a .csv with the following format:
1. First column is the index (from 0 to 10401);
2. Second column is named `income` and contains the predictions (only 0's or 1's) you  got in the previous cell with y_pred.

Example:

    index,income

    0,0

    1,0

    2,1

    ...

    10401,0


Submit it to the competition and check your score there.

In [ ]:
# Assuming your list is named 'boolean_list'


# Replace True by 1 and False by 0
y_pred_new = [1 if value else 0 for value in y_pred]

print(y_pred_new)  # This will print: [1, 0, 1, 1, 0]


[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
df = pd.DataFrame(y_pred_new, columns=["income"])
df.tail()

income
10397       0
10398       0
10399       0
10400       0
10401       0

In [ ]:
df_reset = df.reset_index()


In [ ]:
df_reset.tail()

index  income
10397  10397       0
10398  10398       0
10399  10399       0
10400  10400       0
10401  10401       0

In [ ]:
# Assuming 'df_reset' is the DataFrame you want to save
df_reset.to_csv(PATH + '/Project/adult_output.csv', index=False)
